# Custom Language File for Launcher Customizer

[ejs.app]
title = "SDJ Studios Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaTwitterURL = "https://x.com/martinuxpx"
mediaInstagramURL = "https://www.tiktok.com/"
mediaYouTubeURL = "https://youtube.com/@martinuxpx"
mediaDiscordURL = "https://discord.gg/wr9JuG8Ue2"

[ejs.settings]
sourceGithubLink = "https://github.com/Shisuiicaro/HastaStudiosLauncher"
supportLink = "https://discord.gg/wr9JuG8Ue2"
selectLanguage = "Select a Language"
changeLanguageTitle = "Change the launcher language"
changeLanguageDesc = "You can change the language in the list below. This text will not change if you change the language so you can find your wayback here to change it back"

[ejs.welcome]
welcomeHeader = "Bienvenido a SDJ Studios Launcher"
welcomeDescription = ""
[ejs.overlay]
changedLanguageHeader = "You changed the previous language"